### ISSUE TITLE
update occuring in evaluation

### ISSUE THREAD

**Issue by sridhardkamoji** [Paulescu/hands-on-rl#5]
In notebook: https://github.com/Paulescu/hands-on-rl/blob/main/01_taxi/notebooks/02_q_agent.ipynb

in the evaluation section Cell no 80, 
`next_state, reward, done, info = env.step(action) `
should be 
`state, reward, done, info = env.step(action) `

we should not be doing this  
`agent.update_parameters(state,` action, reward, next_state)

as we are getting the best action from q table

the same thing in cell 86

**Comment by Paulescu** [comment]
And you are super right.
I will find some time this week to fix this.

**Comment by Paulescu** [comment]
I just pushed the changes in #6 
Thanks a lot for raising the issue @sridhardkamoji
